name: Rust Build and Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_check:
    name: Trigobot Carcinized
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27

      - uses: cachix/cachix-action@v15
        with:
            name: trigobot 
            authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
            extraPullNames: nix-community

      - name: Check flake (runs linters, etc.)
        run: nix flake check

      - name: Build
        run: nix build
